@startuml SkinElements



class SkinElement {
    + const unsigned char* data
    + unsigned int size
}

class SkinSprite {
    + const unsigned char* data
    + unsigned int size
    + Definition definition
    + bool isAnimated
}

class SkinAnimated {
    + const frame* data[]
    + unsigned int size
    + Definition definition
    + bool isAnimated
    + unsigned int frames
}


SkinSprite --|> SkinElement : extends

@enduml